FROM openjdk:11
EXPOSE 4200
ADD target/product-webapp.jar /home/abhinay.k.mishra/Learning/telecare-docker/product-webapp.jar
ENTRYPOINT ["java","-jar","/home/abhinay.k.mishra/Learning/telecare-docker/product-webapp.jar"]
