FROM openjdk:11
EXPOSE 8080
ADD target/api-gateway.jar /home/abhinay.k.mishra/Learning/telecare-docker/api-gateway.jar
ENTRYPOINT ["java","-jar","/home/abhinay.k.mishra/Learning/telecare-docker/api-gateway.jar"]
