FROM openjdk:11
EXPOSE 8761
ADD target/eureka-server.jar /home/abhinay.k.mishra/Learning/telecare-docker/eureka-server.jar
ENTRYPOINT ["java","-jar","/home/abhinay.k.mishra/Learning/telecare-docker/eureka-server.jar"]
