FROM openjdk:11
EXPOSE 8888
ADD target/config-server.jar /home/abhinay.k.mishra/Learning/telecare-docker/config-server.jar
ENTRYPOINT ["java","-jar","/home/abhinay.k.mishra/Learning/telecare-docker/config-server.jar"]
