FROM openjdk:11
EXPOSE 8070
ADD target/chat-service.jar /home/abhinay.k.mishra/Learning/telecare-docker/chat-service.jar
ENTRYPOINT ["java","-jar","/home/abhinay.k.mishra/Learning/telecare-docker/chat-service.jar"]
