FROM openjdk:11
EXPOSE 8060
ADD target/appointment-service.jar /home/abhinay.k.mishra/Learning/telecare-docker/appointment-service.jar
ENTRYPOINT ["java","-jar","/home/abhinay.k.mishra/Learning/telecare-docker/appointment-service.jar"]
