FROM openjdk:11
EXPOSE 8075
ADD target/email-service.jar /home/abhinay.k.mishra/Learning/telecare-docker/email-service.jar
ENTRYPOINT ["java","-jar","/home/abhinay.k.mishra/Learning/telecare-docker/email-service.jar"]
