FROM openjdk:11
EXPOSE 9090
ADD target/user-service.jar /home/abhinay.k.mishra/Learning/telecare-docker/user-service.jar
ENTRYPOINT ["java","-jar","/home/abhinay.k.mishra/Learning/telecare-docker/user-service.jar"]
