FROM openjdk:11
EXPOSE 8095
ADD target/authentication-service.jar /home/abhinay.k.mishra/Learning/telecare-docker/authentication-service.jar
ENTRYPOINT ["java","-jar","/home/abhinay.k.mishra/Learning/telecare-docker/authentication-service.jar"]
